development.driver=org.sqlite.JDBC
development.url=jdbc:sqlite:./db/dev.db
development.username=sa
development.password=

test.driver=org.sqlite.JDBC
test.url=jdbc:sqlite:./target/test.db
test.username=
test.password=